#!/usr/bin/env bash

# This script displays information about subdomains.
# Arguments:
#   domain - Domain name to audit (mandatory)
#   subdomain - Specific subdomain to audit (optional)
# Output: 
#   The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

if [ "$#" -eq 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    
    for subdomain in "${subdomains[@]}"; do
        response=$(dig "$subdomain.$1" +short)
        if [[ -n "$response" ]]; then
            record_type=$(dig "$subdomain.$1" +short | awk '{print $2}')
            destination=$(dig "$subdomain.$1" +short | awk '{print $1}')
            sub_domain=$(echo $subdomain | cut -d'-' -f1)
            echo "The subdomain $sub_domain is a $record_type record and points to $destination"
        fi
    done
elif [ "$#" -eq 2 ]; then
    response=$(dig "$2.$1" +short)
    if [[ -n "$response" ]]; then
        record_type=$(dig "$2.$1" +short | awk '{print $2}')
        destination=$(dig "$2.$1" +short | awk '{print $1}')
        sub_domain=$(echo $2 | cut -d'-' -f1)
        echo "The subdomain $sub_domain is a $record_type record and points to $destination"
    fi
fi
